### ISSUE TITLE
Reliability issues

### ISSUE THREAD

**Issue by dagerydoo** [alexruperez/LaunchScreenSnapshot#2]
I was trying out this repo as I was implementing a solution similar to this, but I was hitting a problem on swapping in my secure view (~1 out of 10 times, when going to the carousel view, the secure view was not swapping in). I was stress testing this pod (nice simple interface, by the way), and noticed that this has the same issue: every once in a while, when I double tap home, the screen is not protected.

This is on an iPhone 6 running iOS 11.2. Has anyone else noticed this? I have other workarounds, but none are as desirable the `WillResignActive`/`DidBecomeActive` mechanism, as it allows precise control.

**Comment by dagerydoo** [comment]
As a sanity check, I opened up the app I use for mobile banking, and it did the same thing: I double tapped home and went to the carousel. I figured the bank app would reliably protect my balance, etc. It failed at the **same rate**. This seems like an underlying iOS issue...

**Comment by alexruperez** [comment]
Thanks for the feedback @dagerydoo
